version: 2
updates:
  # Maintain GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "area/cicd"
      - "type/security"
      - "dependencies"

  # Maintain Go module dependencies
  - package-ecosystem: "gomod"
    directory: "/benchmarks"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "area/go"
      - "type/security"
      - "dependencies"

  # Maintain Dockerfile base image dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "area/docker"
      - "type/security"
      - "dependencies"
